//
// Created by Karina Hernandez on 05-oct.-20.
//

#ifndef LAB07_FILES_SERIALIZATION_KARINAHERNANDEZSANCHEZ_BINARYFILE_H
#define LAB07_FILES_SERIALIZATION_KARINAHERNANDEZSANCHEZ_BINARYFILE_H


class BinaryFile {

};


#endif //LAB07_FILES_SERIALIZATION_KARINAHERNANDEZSANCHEZ_BINARYFILE_H
