//
// Created by Karina Hernandez on 05-oct.-20.
//

#ifndef LAB07_FILES_SERIALIZATION_KARINAHERNANDEZSANCHEZ_JSONFILE_H
#define LAB07_FILES_SERIALIZATION_KARINAHERNANDEZSANCHEZ_JSONFILE_H


class JSONFile {

};


#endif //LAB07_FILES_SERIALIZATION_KARINAHERNANDEZSANCHEZ_JSONFILE_H
