//
// Created by Karina Hernandez on 04-oct.-20.
//

#ifndef LAB07_FILES_SERIALIZATION_KARINAHERNANDEZSANCHEZ_PERSON_H
#define LAB07_FILES_SERIALIZATION_KARINAHERNANDEZSANCHEZ_PERSON_H


class Person {
private:
    int id;
    int age;
    string name;
};


#endif //LAB07_FILES_SERIALIZATION_KARINAHERNANDEZSANCHEZ_PERSON_H
