//
// Created by Karina Hernandez on 05-oct.-20.
//

#ifndef LAB07_FILES_SERIALIZATION_KARINAHERNANDEZSANCHEZ_XMLFILE_H
#define LAB07_FILES_SERIALIZATION_KARINAHERNANDEZSANCHEZ_XMLFILE_H


class XMLFile {

};


#endif //LAB07_FILES_SERIALIZATION_KARINAHERNANDEZSANCHEZ_XMLFILE_H
